import { z } from "zod";
declare const envSchema: z.ZodObject<{
    DATABASE_URL: z.ZodString;
    REDIS_URL: z.ZodString;
    NEXTAUTH_SECRET: z.ZodString;
    NEXTAUTH_URL: z.ZodString;
    OPENAI_API_KEY: z.ZodString;
    STRIPE_SECRET_KEY: z.ZodString;
    STRIPE_WEBHOOK_SECRET: z.ZodString;
    STRIPE_PRICE_ID_STARTER: z.ZodString;
    STRIPE_PRICE_ID_GROWTH: z.ZodString;
    STRIPE_PRICE_ID_SCALE: z.ZodString;
    AWS_ACCESS_KEY_ID: z.ZodString;
    AWS_SECRET_ACCESS_KEY: z.ZodString;
    AWS_REGION: z.ZodString;
    AWS_S3_BUCKET: z.ZodString;
    RESEND_API_KEY: z.ZodString;
    DD_API_KEY: z.ZodOptional<z.ZodString>;
    DD_SERVICE: z.ZodOptional<z.ZodString>;
    APP_URL: z.ZodString;
    API_URL: z.ZodString;
    ENCRYPTION_KEY: z.ZodString;
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "production", "test"]>>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "production" | "test";
    DATABASE_URL: string;
    REDIS_URL: string;
    NEXTAUTH_SECRET: string;
    NEXTAUTH_URL: string;
    OPENAI_API_KEY: string;
    STRIPE_SECRET_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
    STRIPE_PRICE_ID_STARTER: string;
    STRIPE_PRICE_ID_GROWTH: string;
    STRIPE_PRICE_ID_SCALE: string;
    AWS_ACCESS_KEY_ID: string;
    AWS_SECRET_ACCESS_KEY: string;
    AWS_REGION: string;
    AWS_S3_BUCKET: string;
    RESEND_API_KEY: string;
    APP_URL: string;
    API_URL: string;
    ENCRYPTION_KEY: string;
    DD_API_KEY?: string | undefined;
    DD_SERVICE?: string | undefined;
}, {
    DATABASE_URL: string;
    REDIS_URL: string;
    NEXTAUTH_SECRET: string;
    NEXTAUTH_URL: string;
    OPENAI_API_KEY: string;
    STRIPE_SECRET_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
    STRIPE_PRICE_ID_STARTER: string;
    STRIPE_PRICE_ID_GROWTH: string;
    STRIPE_PRICE_ID_SCALE: string;
    AWS_ACCESS_KEY_ID: string;
    AWS_SECRET_ACCESS_KEY: string;
    AWS_REGION: string;
    AWS_S3_BUCKET: string;
    RESEND_API_KEY: string;
    APP_URL: string;
    API_URL: string;
    ENCRYPTION_KEY: string;
    NODE_ENV?: "development" | "production" | "test" | undefined;
    DD_API_KEY?: string | undefined;
    DD_SERVICE?: string | undefined;
}>;
export type Env = z.infer<typeof envSchema>;
export declare function validateEnv(): Env;
export {};
